# https://docs.travis-ci.com/user/customizing-the-build/

if: tag IS blank
os:
  - linux
  - osx
sudo: false
language: node_js
node_js:
  - "10"
  - "12"
  - "15"
install:
  - yarn install
script:
  - node --version
  - npm --version
  - yarn --version
  - yarn run lib
